A17 and A27ab added
FlyBase/harvdev-proforma-parser pull request #201
Opened 2022-05-20 17:31 UTC by ianlongden

2022-05-26 18:49 UTC, gildossantos requested changes

2022-05-26 18:49 UTC, gildossantos commented on src/chado_object/aberration/break_point.py
> +                value += "-{}".format(position['strand'])
I think this is for new "reported_genomic_loc" featureprops. In this case, when strand is indicated (n=4), it's appended as "(-)" or "(+)".
It's not clear to me that `position[strand]` value will be either a `-` or `+`. Can you point me to the code?
Also, that `+/-` char should be between brackets, not attached after a `-` char, as you have here.

2022-05-26 18:49 UTC, gildossantos commented on src/chado_object/aberration/chado_aberration.py
> +        geno, _ = get_or_create(self.session, Genotype, uniquename=self.feature.name)
Need to use sgml for genotype uniquenames, not feature names. Brackets have to be converted to `<up>/</up>`, greek chars need to be in `&agr;`-type form, etc.
e.g., for genotype_id=372049 for aberration `Df(1)Vinc[2]`, we have genotype.uniquename = `Df(1)Vinc<up>2</up>`.

2022-05-26 18:49 UTC, gildossantos commented on src/chado_object/aberration/chado_aberration.py
> +        chrom, _ = get_or_create(self.session, Feature,
I don't think you should be creating chrom, here or anywhere, ever. We only make new chrom with new reference assembly scaffolds.

2022-05-26 18:49 UTC, gildossantos commented on src/chado_object/aberration/chado_aberration.py
> +                              chromosome_id=chrom.feature_id,
For all feature_genotypes, we have only one chromosome_id: `feature_id=23159230, name=unspecified`.

2022-06-01 13:19 UTC, gildossantos commented on src/chado_object/aberration/chado_aberration.py
> +        chrom, _ = get_or_create(self.session, Feature,
My mistake. I was confusing new "chromosome" features with "golden_path". The latter are associated with reference genome assemblies and should not be made via proforma. But the former can be created by proforma (though rare). So this is ok.

2022-06-01 13:36 UTC, gildossantos commented on src/chado_object/aberration/chado_aberration.py
> +                              chromosome_id=chrom.feature_id,
Just talked to Ian. This is ok, as in perl parser and in the yaml files (new python), the chrom is hard-coded as "unspecified".

2022-06-07 13:58 UTC, ianlongden commented on src/chado_object/aberration/break_point.py
> +                value += "-{}".format(position['strand'])
Warning is now given and the strand is ignored.

2022-06-07 22:47 UTC, gildossantos approved these changes

2022-06-07 22:48 UTC, merged