Flags in pub fix and fix for pubchem_abstract conversion
FlyBase/harvdev-proforma-parser pull request #203
Opened 2022-08-17 20:46 UTC by ianlongden

2022-08-18 15:16 UTC, gildossantos requested changes
Odd - PR says 4 files changed, but it shows same file twice:
src/validation/yaml/publication.yaml

2022-08-18 15:16 UTC, gildossantos commented on src/validation/yaml/publication_new.yaml
> +  allowed: [RNAi,cell_cult, cell_cult::DONE, cell_line, cell_line::DONE, chemical, chemical::Done, cis_reg, cis_reg::DONE,
should be `chemical::DONE` (all uppercase), not `chemical::Done`

2022-08-18 15:17 UTC, gildossantos reviewed
oh - why two similar file? publication.yaml and publication_new.yaml. Should one be deleted?

2022-08-18 15:36 UTC, gildossantos approved these changes

2022-08-18 15:36 UTC, merged

2022-08-19 10:09 UTC, gm119 commented
the values you have in the two yaml files in the allowed array are not current - there are several that are no longer allowed, and some look like typos that got into the database by mistake, so they should not be treated as allowed values.
current allowed values for P41 are: (from  curation_docs/curation_manual_2.html#p41.-flag-harvard-for-curation-softcv-harvcur )

a. the following can also have ::DONE appended

wt_exp
neur_exp
gene_model
phys_int
cis_reg
genom_feat
disease
diseaseHP
diseaseF
dataset
cell_line
cell_line(commercial)
cell_line(stable)


b. allowed values for P40 are also not correct, current values allowed from cur man are:

    nocur
    nocur_abs
    merge
    split
    rename
    new_char
    new_al
    new_transg
    pheno
    gene_group
    noGOcur
    pheno_chem
    pheno_anat
    pathway

2022-08-19 12:20 UTC, ianlongden commented
I will fix these now.