Start seqfeat
FlyBase/harvdev-proforma-parser pull request #209
Opened 2022-11-15 20:20 UTC by ianlongden

2022-11-17 18:21 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +  regex: ^(FBsf\d{7}|new)$
FBsf IDs are an exception to our normal FB IDs - they always have 10 digits, not 7.

2022-11-17 18:33 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +  if_new_required: SF1f # if new required or new pub
I think we're being led astray by some old and inaccurate seq feat docs.

This requirement is, oddly, more stringent than for genes. Neither peeves nor the parser care if SF1b is empty, and I think that's how it should be.

So please remove this `if_new_required` line. Please just make it `required: False`.

That's my two cents as a seq feat curator.

2022-11-17 18:36 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
Looks like `SF1g` is specified three times - should only be once?

2022-11-17 18:37 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF3b:
Species should be required if new. This does not seem to be specified here.

2022-11-17 18:45 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
should be `SF1h` here.

2022-11-17 18:45 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
```suggestion
SF1i:
```

2022-11-17 18:46 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF3b:
You can't make a new seqfeat without specifying the species

2022-11-17 18:48 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF4d:
It looks like Gillian has removed SF4d-f from the proforma, as per email. Did you implement code for this because I said it could be useful? If so, we'll need to get Gillian to revert those changes to the proforma template on the SVN.

2022-11-17 18:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF22a:
All SF22 are now obsolete - please remove.

2022-11-17 19:48 UTC, ianlongden commented on src/validation/yaml/seqfeat.yaml
> +  regex: ^(FBsf\d{7}|new)$
Thanks, Done.

2022-11-17 19:53 UTC, ianlongden commented on src/validation/yaml/seqfeat.yaml
> +SF3b:
Done. Default of Dmel was used in the parser but if peeves was complaining then that is the correct thing to do.

2022-11-17 19:57 UTC, ianlongden commented on src/validation/yaml/seqfeat.yaml
> +SF4d:
Not coded as per curation instructions. But left in incase we do fix it. If SF4[def] are used then an error message is displayed that explains this and asked user to contact Harvdev if required. Hopefully that should be okay.

2022-11-17 19:59 UTC, ianlongden commented on src/validation/yaml/seqfeat.yaml
> +SF21a:
Removed.

2022-11-17 19:59 UTC, ianlongden commented on src/validation/yaml/seqfeat.yaml
> +SF22a:
Done.

2022-11-17 20:13 UTC, gildossantos requested changes

2022-11-17 20:13 UTC, gildossantos commented on src/chado_object/seqfeat/chado_seqfeat.py
> +        if self.has_data(id_key) and self.process_data[id_key]['data'][FIELD_VALUE] != "new":
I wonder if there's an issue with how merge and new actions interact.

When a curator wants to do a merge, do they put "new" in SF1f? I think so, and so does Peeves (though the docs suck so I'm not sure). If so, what happens in the code?

My read of the code is that a new "merge" seq feat gets created, then there's an attempt to make another new seqfeat which would give a critical error because the desired name is already taken from the merge seq feat.

Maybe I'm missing something, but if not, then we might need to make sure we don't make new if merge action is to be taken?

2022-11-17 20:51 UTC, ianlongden commented on src/chado_object/yml/seqfeat.yml
> +  allowed_types: ['transcript']
Replacing all allowed_types with FBxx instead to cover all instances. i.e. transcript => FBtr

2022-11-17 20:51 UTC, ianlongden commented on src/chado_object/yml/seqfeat.yml
> +  allowed_types: ['engineered_plasmid']
FBpp now used.

2022-11-17 20:52 UTC, ianlongden commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
Done.

2022-11-21 13:06 UTC, ianlongden commented on src/chado_object/seqfeat/seqfeat_process_sets.py
> +        # Now create the featureloc
yaml file now states that ONLY 6 is allowed.

2022-11-21 13:21 UTC, ianlongden commented on src/chado_object/seqfeat/chado_seqfeat.py
> +        if self.has_data(id_key) and self.process_data[id_key]['data'][FIELD_VALUE] != "new":
I am going to add test data and and add tests for this. So may take a little while. I will update when done.
It follows other feature merging. And uses the same code but this could be different so adding tests.

2022-11-22 13:55 UTC, ianlongden commented on src/chado_object/seqfeat/chado_seqfeat.py
> +        if self.has_data(id_key) and self.process_data[id_key]['data'][FIELD_VALUE] != "new":
Making SF1f to HAVE to be "new" if SF1g is specified. Peeves says this and is the source of truth not the docs!

2022-11-22 14:35 UTC, ianlongden commented on src/chado_object/seqfeat/chado_seqfeat.py
> +        if self.has_data(id_key) and self.process_data[id_key]['data'][FIELD_VALUE] != "new":
As for the naming a new one to one that is being merged, I think we should be okay. The unique bit is :-     "feature_synonym_synonym_id_key" UNIQUE CONSTRAINT, btree (synonym_id, feature_id, pub_id)
so as long as the pub is different we should be okay. Writing tests for this now. Merged ones are made obsolete so I guess the test scripts that run after epicycle load only check for feature that are not obsolete when checking unique names.

2022-11-22 17:01 UTC, ianlongden commented on src/chado_object/seqfeat/chado_seqfeat.py
> +            self.load_synonym(symbol_key, cvterm_name='fullname', overrule_removeold=True)
Done, tests added.

2022-11-22 20:15 UTC, ianlongden commented
All done. No rush. Next week is fine.

2022-11-28 16:36 UTC, gildossantos reviewed
Have all the changes been committed? There are comments that refer to changes that I'm not seeing.

2022-11-28 16:36 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +  regex: ^(FBsf\d{7}|new)$
You said done but it looks like we still have `\d{7}` in the code?

2022-11-28 16:36 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF3b:
I don't see the change in the yaml that makes a species entry required if new.

2022-11-28 16:55 UTC, gildossantos approved these changes
It all looks great. All issues have been resolved in full, except for one. SF4b should allow for any release, and write featureprop in all cases, but write featureloc only if release == '6'. That said, we rarely curate non-release 6 coordinates anymore, so I'm ok with delaying this implementation for now.

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF3b:
now I see it.

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +  regex: ^(FBsf\d{7}|new)$
it is done - I needed to refresh my page?

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +  if_new_required: SF1f # if new required or new pub
This spec has been removed.

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
Done.

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF3b:
I see the change.

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
DOne

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF1g:
thanks

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF4d:
makes sense.

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF21a:
done

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +SF22a:
confirming

2022-11-28 16:55 UTC, gildossantos commented on src/validation/yaml/seqfeat.yaml
> +    allowed: ['6']
```suggestion
    allowed: ['3', '4', '5', '6']
```

2022-11-28 16:55 UTC, gildossantos commented on src/chado_object/seqfeat/seqfeat_process_sets.py
> +        # Now create the featureloc
Actually, we should allow many values (3-6), and make the featureprop in all cases, but only make the featureloc if release == 6. Sorry that I was not clear about that.

2022-11-28 16:55 UTC, gildossantos commented on src/chado_object/yml/seqfeat.yml
> +  allowed_types: ['transcript']
This looks good.

2022-11-28 16:55 UTC, gildossantos commented on src/chado_object/yml/seqfeat.yml
> +  allowed_types: ['engineered_plasmid']
ok

2022-11-28 16:55 UTC, gildossantos commented on src/chado_object/seqfeat/seqfeat_process_sets.py
> +        featuresrc, is_new = get_or_create(self.session, Feature, name=arm_name, type_id=arm_type_id)
ok

2022-11-28 16:55 UTC, gildossantos commented on src/chado_object/seqfeat/chado_seqfeat.py
> +            self.load_synonym(symbol_key, cvterm_name='fullname', overrule_removeold=True)
ok

2022-11-28 16:55 UTC, gildossantos commented on src/chado_object/seqfeat/chado_seqfeat.py
> +            self.load_synonym(symbol_key, cvterm_name='fullname')
confirming

2022-11-28 16:55 UTC, merged