Removal of CH3d, CH3a is now a list. synonym fixes
FlyBase/harvdev-proforma-parser pull request #235
Opened 2023-05-19 15:36 UTC by ianlongden

2023-05-23 14:15 UTC, gildossantos commented on src/chado_object/feature/chado_feature.py
>              if 'subscript' in self.process_data[key] and not self.process_data[key]['subscript']:
```suggestion
            if 'subscript' in self.process_data[key].keys() and self.process_data[key]['subscript'] is False:
```
I think something like the above suggestion is more explicit, and it may be helpful to someone like me who is unfamiliar with the code. But maybe I just need to get more familiar with your style, and I'm not suggesting it's a good idea to try and change similar lines throughout the code.

2023-05-23 14:28 UTC, gildossantos commented on src/chado_object/feature/chado_feature.py
> +                                                     name, cv_name, cvterm_name, pub_id,
I like the `greek_to_sgml` step here, in case a Greek char gets into the proforma somehow.
But this only happens if we have `subscript: False`, correct? If `subscript: True`, or `subscript` is not defined for some feature's synonym field, then it defaults to the behavior of the `fs_add_by_synonym_name_and_type` function, which does not have the extra `greek_to_sgml` catch - I think this will be problematic when we expand the python parser to other features (beyond chemicals) where we do not have `subscript: False`.
Suggestion - add `greek_to_sgml` step in `fs_add_by_synonym_name_and_type` function.

2023-05-23 19:28 UTC, gildossantos requested changes

2023-05-23 19:29 UTC, gildossantos requested changes
Please address the comments on specific code elements, and fix if necessary (or just tell me where I've misunderstood).

2023-05-23 20:03 UTC, ianlongden commented on src/chado_object/feature/chado_feature.py
>              if 'subscript' in self.process_data[key] and not self.process_data[key]['subscript']:
I have created a new method subscript_convert which has the format as requested. This is reused in various places so hopefully will be less code repetition and easier to see what is going on.

2023-05-23 20:15 UTC, ianlongden commented on src/chado_object/feature/chado_feature.py
> +                                                     name, cv_name, cvterm_name, pub_id,
Agreed and changed.

2023-05-24 10:45 UTC, ianlongden commented on src/chado_object/chemical/chado_get_create.py
> +            identifier, name, error_msg = self.split_identifier_and_name(item[FIELD_VALUE], key)
1 (bob) fixed. 2 name just has to match the chemical name or a synonym, checks done later. 3.[1,2] (DBxref.description) checks are done via the name and synonyms not the description. I think this should be enough.

2023-05-24 10:48 UTC, ianlongden commented on src/chado_object/chemical/chado_get_create.py
> +                join(Db).filter(Db.name == identifier,
Good spot resolved. Actually added Feature.is_obsolete.is_(False) too to filter.

2023-05-24 11:05 UTC, ianlongden commented on src/chado_object/chemical/chado_chem.py
>          identifier_unprocessed = sgml_to_unicode(identifier_unprocessed)
Done.

2023-05-24 11:12 UTC, ianlongden commented on src/chado_object/chemical/chemical_lookup.py
>      process_key: Key to use to get data , should be CH3a or CH3d
Done thanks.

2023-05-25 16:54 UTC, ianlongden commented on src/chado_object/chemical/chemical_lookup.py
> +        identifier_unprocessed = sgml_to_unicode(identifier_unprocessed)
done.

2023-05-25 17:37 UTC, gildossantos approved these changes
Looks good. Thanks!

2023-05-25 17:37 UTC, gildossantos commented on src/chado_object/general/synonym.py
> +    log.debug(f"BOB: GEN pretest fs_add_by_synonym_name_and_type {synonym_name} {synonym_sgml}")
Double checking that you still want BOB here in debug output.

2023-05-25 17:37 UTC, merged