Pub flags now use lookups to ensure only those in the pairs are chang…
FlyBase/harvdev-proforma-parser pull request #241
Opened 2023-09-05 20:47 UTC by ianlongden

…ed (i.e. chemical -> chemical::DONE). Warnings given for things that seem to not make sense.

2023-11-15 15:20 UTC, gildossantos requested changes

2023-11-15 15:20 UTC, gildossantos commented on src/chado_object/chado_pub.py
> +                flag_done_found.value = item[FIELD_VALUE]
So a curator can overwrite an old flag without using !c? If that's the case, I disagree with this implementation as it contradicts accepted curator practice. It could easily be done by mistake - curator reads a paper and tries to add a flag without checking to see if it's done first, which I can see happening a lot.

2023-11-15 15:20 UTC, gildossantos commented on src/chado_object/chado_pub.py
> +                flag_done_found.value = item[FIELD_VALUE]
I think in this case, there should be a warning, and a 2nd flag (not ::DONE) gets added, leaving the original ::DONE in place. This is how the perl parser works.

2023-11-15 15:23 UTC, gm119 commented on src/chado_object/chado_pub.py
> +                flag_done_found.value = item[FIELD_VALUE]
I completely agree with Gil, for the reasons he said

2024-01-12 15:13 UTC, ianlongden commented on src/chado_object/chado_pub.py
> +                flag_done_found.value = item[FIELD_VALUE]
I am going to remove this, obviously not fit for purpose.

2024-01-22 15:41 UTC, ianlongden commented on src/chado_object/chado_pub.py
> +                flag_done_found.value = item[FIELD_VALUE]
Need to revisit this as the old code is causing problems.
If the proforma wants to set a flag and it is already set should I just ignore it and carry on with a message  or give a critical error and stop.
Also now the code will give a critical error if you try and change a flag without the !c.
I presume this is what is now needed.

2024-01-23 16:12 UTC, gildossantos requested changes
I _think_ code needs to be added to allow a curator to bangc a DONE flag back to not done. Also questions about what to do with duplicate pubprops that I want to double check on.

2024-01-23 16:12 UTC, gildossantos commented on src/chado_object/chado_pub.py
> +        flag_status = item[FIELD_VALUE].split('::')
I want to confirm that HarvCur will only use `::` to separate a flag from the `DONE` suffix: i.e., that there are not other suffices in use that are appended with an intervening `::`.

2024-01-23 16:12 UTC, gildossantos commented on src/chado_object/chado_pub.py
> +            if flag_done_found:
Do we need a step that checks the `bangc` boolean here to allow for conversion of something like `phys_int::DONE` to `phys_int` here if `bangc=True`?

2024-01-23 16:34 UTC, gildossantos commented on src/chado_object/chado_pub.py
> +        flag_status = item[FIELD_VALUE].split('::')
OK - curators can only use `::DONE` in the proforma, so all good here.

2024-01-23 16:56 UTC, gm119 commented on src/chado_object/chado_pub.py
> +            if flag_done_found:
I'm a bit concerned about what will happen if a given triage flag field (P40-P43) has multiple values in chado already, and the curator is just trying to change one of them to ::DONE - since bangc works by removing everything for that FBrf+proforma+field combo, and then adding back everything, then the following is a common kind of procedure. I'm not sure whether the code is doing to do the right thing for that so am asking question here.
example:
1. P41 slot in chado has phys_int, genom_feat
2. curator has done phys_int curation so wants to change phys_int to DONE while leaving genom_feat as is.
3. the correct thing to put in the proforma in the P41 field in this case would be: phys_int::DONE and genom_feat with bangc - the curator needs to 'add back' genom_feat, otherwise it will 'disappear' from chado (because the bangc will remove everything first, before adding back whatever is filled in in the P41 field)

will the new parser allow this

2024-01-23 17:46 UTC, ianlongden commented
Bangc in the python parser for flags (P40 -> P43) currently  works differently in this branch.

I considered these as prop flags, i.e. can only have one flag::value per pub.

The normal procedure here at Harvard was having problems as without having this act as a  flag it could add 
multiple copies of the same data which was having problems later when retrieving data.

So to replicate your example here with the new branch.


> P41 slot in chado has phys_int, genom_feat
> curator has done phys_int curation so wants to change phys_int to DONE while leaving genom_feat as is.
> the correct thing to put in the proforma in the P41 field in this case would be: phys_int::DONE
NOTE: here genom_feat remains as it only replaces the values for the “flag” phys_int.


Maybe I need a re rethink or have a different field operate this way to differentiate.



> On 23 Jan 2024, at 11:56, gm119 ***@***.***> wrote:
> 
> 
> @gm119 commented on this pull request.
> 
> In src/chado_object/chado_pub.py <https://github.com/FlyBase/harvdev-proforma-parser/pull/241#discussion_r1463626141>:
> 
> > +                    item,
> +                    f'{flag_status[0]}::DONE being set for {self.pub.uniquename} but {flag_status[0]} NOT found. Setting flag anyway')
> +                pub_prop, _ = get_or_create(
> +                    self.session, Pubprop,
> +                    pub_id=self.pub.pub_id,
> +                    value=item[FIELD_VALUE],
> +                    type_id=cvterm.cvterm_id
> +                )
> +            elif flag_found:
> +                if not bangc:
> +                    self.critical_error(item,
> +                                        f'{flag_status[0]} found so cannot set to DONE without bangc')
> +                    return
> +                flag_found.value = item[FIELD_VALUE]
> +        else:
> +            if flag_done_found:
> I'm a bit concerned about what will happen if a given triage flag field (P40-P43) has multiple values in chado already, and the curator is just trying to change one of them to ::DONE - since bangc works by removing everything for that FBrf+proforma+field combo, and then adding back everything, then the following is a common kind of procedure. I'm not sure whether the code is doing to do the right thing for that so am asking question here.
> example:
> 
> P41 slot in chado has phys_int, genom_feat
> curator has done phys_int curation so wants to change phys_int to DONE while leaving genom_feat as is.
> the correct thing to put in the proforma in the P41 field in this case would be: phys_int::DONE and genom_feat with bangc - the curator needs to 'add back' genom_feat, otherwise it will 'disappear' from chado (because the bangc will remove everything first, before adding back whatever is filled in in the P41 field)
> will the new parser allow this
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/FlyBase/harvdev-proforma-parser/pull/241#discussion_r1463626141>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA7X4RXMPWSB2NBEW324D53YP7TVPAVCNFSM6AAAAAA4MKSPOCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMZZGM3DENJSGU>.
> You are receiving this because you modified the open/close state.
>

2024-01-23 18:04 UTC, gm119 commented
thanks for the explanation about my example, thats reassuring !

If you do make a new kind of correction procedure in the new parser for this kind of maneouvre in these fields please could it have a different name in the code so its clear that the actions that happen in the db are different to avoid confusion.

Also this new maneouvre could have a different letter code between the ! and the field (i.e. not c) to show its different, that way it'll be completely clear to curators that they are doing something different not the regular bangc (I can see that there might be cases where we would genuinely want to bangc the whole field e.g. if all the flags for the pub were wrong)

(we have a long-standing wish to be able to do a different kind of correction, where we explicitly state what data we want to delete for a fbrf+thing+field combination, using a 'd' instead of 'c', i.e. bangd, but I don't think this is quite that either as its transforming a single flag from one value to another - what fun !)

2024-01-23 18:56 UTC, ianlongden commented
So I will remove this PR now and use this new code in a new field or maybe !f for flags. Not decided yet. Also no rush for this , I will add a fix for the current flags to fix what the Harvard curators are doing at the moment.

2024-01-23 18:56 UTC, closed without merging

2024-01-23 19:12 UTC, gm119 commented
can I request that before any work is done on a new field or a new correction mechanism that we have a meeting that involves cambridge curators as well as harvard curators - these flags drive all our prioritizaton stuff, and I would want to make sure that all the curators are on the same page before work on new fields etc. is started, both to make sure it doens't impact  on the prioritisation scripts in an unexpected way, but also that any new field/correction procedure would also work for camcur when in the future we eventually switch to the new parser.

Also, it would be good to understand why harvard curators are having problems, as  camcur also often bangc these triage flag fields during thin curation, but I don't think we're having problems with doing the bangc or in retreiving the flags for prioritisation (even flags that are technically harvard P41/P43 'harvard' flags) so maybe there is some difference in curation practise happening (I guess its probably mostly that we're not adding the ::DONE, but we still use flags that can end up with ::DONE for our prioritisation without an issue)

2024-01-23 19:41 UTC, ianlongden commented
Seems reasonable. I think the main problem which will be solved shortly is that chia does not know about chemical flag.
 This is used by the harvard curators mostly in the proforma due to this. One e added it will not be. Aproblme and we can ignore this whole thing :-)

-Ian.


> On 23 Jan 2024, at 14:12, gm119 ***@***.***> wrote:
> 
> 
> can I request that before any work is done on a new field or a new correction mechanism that we have a meeting that involves cambridge curators as well as harvard curators - these flags drive all our prioritizaton stuff, and I would want to make sure that all the curators are on the same page before work on new fields etc. is started, both to make sure it doens't impact on the prioritisation scripts in an unexpected way, but also that any new field/correction procedure would also work for camcur when in the future we eventually switch to the new parser.
> 
> Also, it would be good to understand why harvard curators are having problems, as camcur also often bangc these triage flag fields during thin curation, but I don't think we're having problems with doing the bangc or in retreiving the flags for prioritisation (even flags that are technically harvard P41/P43 'harvard' flags) so maybe there is some difference in curation practise happening (I guess its probably mostly that we're not adding the ::DONE, but we still use flags that can end up with ::DONE for our prioritisation without an issue)
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/FlyBase/harvdev-proforma-parser/pull/241#issuecomment-1906752954>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AA7X4RX3RLCNBUALDAXU22DYQADTBAVCNFSM6AAAAAA4MKSPOCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBWG42TEOJVGQ>.
> You are receiving this because you modified the open/close state.
>